### ISSUE TITLE
Option to change layout overlay similar to regular chat?

### ISSUE THREAD

**Issue by StoneColeQ** [thwonghin/live-chat-overlay#270]
I would love if this extension could just be to the side of the screen scrolling up like the regular chat. Here's an extension similar for twitch.

https://github.com/chylex/Transparent-Twitch-Chat

Basically a transparent youtube chat, so we can read chat while in fullscreen mode but not have it be so distracting. If this feature is added, usernames next to the messages would be nice as well as a smaller font would be nice.

**Comment by thwonghin** [comment]
Thanks for your suggestion!

Actually I have planned feature just like you have described, it is temporarily called ["Vertical flow mode"](https://github.com/thwonghin/live-chat-overlay/issues/5). I will add the details you mentioned in that issue.
